"""empty message

Revision ID: 4ba221570a53
Revises: a85ca0487db3
Create Date: 2024-06-19 22:18:17.611702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ba221570a53"
down_revision = "a85ca0487db3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "calendar_availability_association", ["calendar_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "calendar_availability_association", type_="unique")
    # ### end Alembic commands ###
